services:
  
  match_app:
    container_name: match-app
    build: .
    network_mode: host
    depends_on:
      - postgres_db # make sure that postgres is up before the app, so it can connect
  
  postgres_db:
    image: postgres:latest
    container_name: postgres-db
    env_file:
      - path: ./server/.env
    network_mode: host
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
volumes:
  postgres_data:
    driver: local